### PR TITLE
add Step Functions examples

### PR DESCRIPTION
**Pull request by ymwjbxxq**
*Description of changes:*
I added two examples for AWS Step Functions:

1. startExecution
2. stopExecution

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution under the terms of your choice.

### CODE REVIEW

**Comment by Velfi** [comment]
Hey, thanks for submitting this example. We currently have our examples in three separate GitHub repositories and are working on consolidating them. I'm going to leave this open until that consolidation is complete and then I might need you to re-submit it to a different repo. I'll reply with an update when we get there.

**Comment by jdisanti** [comment]
Thank you for your patience while we consolidated our examples. They are now mastered in the [awsdocs/aws-doc-sdk-examples](https://github.com/awsdocs/aws-doc-sdk-examples/tree/main/rust_dev_preview) repository. If you want to, you can open a pull request there for this change, or let me know if you like me to do it. Thank you!

**Comment by ymwjbxxq** [comment]
> Thank you for your patience while we consolidated our examples. They are now mastered in the [awsdocs/aws-doc-sdk-examples](https://github.com/awsdocs/aws-doc-sdk-examples/tree/main/rust_dev_preview) repository. If you want to, you can open a pull request there for this change, or let me know if you like me to do it. Thank you!

I will do it at least I can say that I have a contributed

**Comment by ymwjbxxq** [comment]
@jdisanti I did it
https://github.com/awsdocs/aws-doc-sdk-examples/pull/2762

**Pull request closed without merging**
